services:
  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      - employee_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee_db:5432/employee_manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  frontend:
    build:
      context: src/main/frontend/
    container_name: frontend
    ports:
      - "4200:4200"

  employee_db:
    image: 'postgres:alpine'
    container_name: employee_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee_manager